In [10]:
# pip install tensorflow==2.0

In [11]:
# import tensorflow as tf
# print(tf.__version__)

# Importing Libraries 

In [9]:
import tensorflow as tf
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import MinMaxScaler 
import sys
np.set_printoptions(threshold=sys.maxsize)

# Data

In [4]:
data = pd.read_excel("todoData.xlsx", date_parser=True)
data.head()

Date  bread  egg  waffles  butter  milk  yogurt  burrito  cereal  \
0 2018-01-01      1    1        1       1     1       1        0       1   
1 2018-01-02      1    0        0       0     1       1        0       0   
2 2018-01-03      0    0        0       0     1       1        0       0   
3 2018-01-04      1    1        0       0     1       0        0       0   
4 2018-01-05      1    1        0       0     1       1        0       1   

   cheese  ...  strawberry  peach  coriander  mint  tomato  onion  potatoes  \
0       0  ...           0      1          1     0       1      1         1   
1       1  ...           0      0          1     0       0      0         0   
2       0  ...           0      0          0     0       1      0         0   
3       0  ...           0      0          1     1       1      0         0   
4       0  ...           1      1          1     0       1      0         0   

   garlic  ginger  pepper  
0       1       1       0  
1       0       0       0  
2       0       0       0  
3       0       0       0  
4       1       1       1  

[5 rows x 30 columns]

# Training Data

In [6]:
#train data before 2019-06-30

training_data = data[data["Date"]< "2019-06-30"].copy()
training_data

Date  apple  burger  chocolate  ...  mutton  spaghetti  wings   Test
0   2018-01-01      0       1          1  ...       1          0      1      1
1   2018-01-02      0       1          1  ...       0          1      1      1
2   2018-01-03      0       1          0  ...       1          1      1      0
3   2018-01-04      0       0          0  ...       1          1      1      1
4   2018-01-05      0       0          0  ...       0          1      1      1
..         ...    ...     ...        ...  ...     ...        ...    ...    ...
540 2019-06-25      0       1          1  ...       0          1      1      1
541 2019-06-26      0       1          0  ...       1          1      1      1
542 2019-06-27      1       0          1  ...       1          1      1      0
543 2019-06-28      1       1          0  ...       1          1      1      1
544 2019-06-29      1       0          1  ...       0          1      1      1

[545 rows x 31 columns]

# Testing Data 

In [7]:
#test data after 2019-06-29

testing_data = data[data["Date"]>"2019-06-29"].copy()
testing_data

Date  apple  burger  chocolate  ...  mutton  spaghetti  wings   Test
545 2019-06-30      1       1          0  ...       1          1      1      0
546 2019-07-01      1       0          1  ...       0          1      1      1
547 2019-07-02      1       1          1  ...       1          1      1      1
548 2019-07-03      1       1          1  ...       0          1      1      0
549 2019-07-04      1       1          0  ...       1          1      1      1
..         ...    ...     ...        ...  ...     ...        ...    ...    ...
725 2019-12-27      1       1          1  ...       1          1      1      0
726 2019-12-28      1       0          1  ...       1          1      1      1
727 2019-12-29      1       1          1  ...       1          1      1      1
728 2019-12-30      1       1          0  ...       0          1      1      0
729 2019-12-31      1       0          1  ...       1          1      1      0

[185 rows x 31 columns]

# Removing Date Columns From Train Data

In [8]:
#removing unnecessary columns

train_data = training_data.drop(["Date"], axis=1)
train_data

apple  burger  chocolate  donuts  ...  mutton  spaghetti  wings   Test
0        0       1          1       0  ...       1          0      1      1
1        0       1          1       1  ...       0          1      1      1
2        0       1          0       0  ...       1          1      1      0
3        0       0          0       1  ...       1          1      1      1
4        0       0          0       0  ...       0          1      1      1
..     ...     ...        ...     ...  ...     ...        ...    ...    ...
540      0       1          1       0  ...       0          1      1      1
541      0       1          0       1  ...       1          1      1      1
542      1       0          1       0  ...       1          1      1      0
543      1       1          0       1  ...       1          1      1      1
544      1       0          1       0  ...       0          1      1      1

[545 rows x 30 columns]

# Normalizing Values

In [9]:
#normalizing values 

scaler = MinMaxScaler()
train_data = scaler.fit_transform(train_data)
train_data

array([[0., 1., 1., ..., 0., 1., 1.],
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 1., 0., ..., 1., 1., 0.],
       ...,
       [1., 0., 1., ..., 1., 1., 0.],
       [1., 1., 0., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.]])

# Preparing Training Data 

In [0]:
x_train = []
y_train = []

In [7]:
# training on 3 days then predciting 4th value

for i in range (3, train_data.shape[0]):
    x_train.append(train_data[i-3:i])
    y_train.append(train_data[i])
    
# train_data[i]

NameError: name 'train_data' is not defined

In [0]:
x_train , y_train = np.array(x_train), np.array(y_train)

In [14]:
x_train.shape

(542, 3, 30)

In [15]:
y_train.shape

(542, 30)

# Building Model

In [0]:
# building LSTM network

from tensorflow.keras import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

regressor = Sequential()

regressor.add(LSTM(units = 60, activation = "relu", return_sequences = True, input_shape= (x_train.shape[1],29)))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = 60, activation = "relu", return_sequences = True))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = 80, activation = "relu", return_sequences=True))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = 120, activation = "relu"))
regressor.add(Dropout(0.2))
regressor.add(Dense(29, activation='sigmoid'))

In [17]:
regressor.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 3, 60)             21840     
_________________________________________________________________
dropout (Dropout)            (None, 3, 60)             0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 3, 60)             29040     
_________________________________________________________________
dropout_1 (Dropout)          (None, 3, 60)             0         
_________________________________________________________________
lstm_2 (LSTM)                (None, 3, 80)             45120     
_________________________________________________________________
dropout_2 (Dropout)          (None, 3, 80)             0         
_________________________________________________________________
lstm_3 (LSTM)                (None, 120)               9

In [0]:
#compiling the regressor model

regressor.compile(optimizer="adam", loss="binary_crossentropy", metrics=["acc"])

In [19]:
#training the the model

regressor.fit(x_train, y_train, epochs=30, batch_size=12)

Train on 542 samples
Epoch 1/30
542/542 [==============================] - 7s 12ms/sample - loss: 0.6814 - acc: 0.5724
Epoch 2/30
542/542 [==============================] - 1s 1ms/sample - loss: 0.6479 - acc: 0.5794
Epoch 3/30
542/542 [==============================] - 1s 1ms/sample - loss: 0.6410 - acc: 0.5795
Epoch 4/30
542/542 [==============================] - 1s 1ms/sample - loss: 0.6385 - acc: 0.5819
Epoch 5/30
542/542 [==============================] - 1s 1ms/sample - loss: 0.6375 - acc: 0.5845
Epoch 6/30
542/542 [==============================] - 1s 1ms/sample - loss: 0.6370 - acc: 0.5827
Epoch 7/30
542/542 [==============================] - 1s 1ms/sample - loss: 0.6354 - acc: 0.5843
Epoch 8/30
542/542 [==============================] - 1s 1ms/sample - loss: 0.6350 - acc: 0.5772
Epoch 9/30
542/542 [==============================] - 1s 1ms/sample - loss: 0.6331 - acc: 0.5855
Epoch 10/30
542/542 [==============================] - 1s 1ms/sample - loss: 0.6318 - acc: 0.5858
Epoch 1

# Preparing Test Data 

In [0]:
# preparing test data 

# we need to have last 3 days of training data to predict the first test data

past_3_days = training_data.tail(3)

df = past_3_days.append(testing_data, ignore_index = True)

# df

Date  apple  burger  chocolate  ...  mutton  spaghetti  wings   Test
0   2019-06-27      1       0          1  ...       1          1      1      0
1   2019-06-28      1       1          0  ...       1          1      1      1
2   2019-06-29      1       0          1  ...       0          1      1      1
3   2019-06-30      1       1          0  ...       1          1      1      0
4   2019-07-01      1       0          1  ...       0          1      1      1
..         ...    ...     ...        ...  ...     ...        ...    ...    ...
183 2019-12-27      1       1          1  ...       1          1      1      0
184 2019-12-28      1       0          1  ...       1          1      1      1
185 2019-12-29      1       1          1  ...       1          1      1      1
186 2019-12-30      1       1          0  ...       0          1      1      0
187 2019-12-31      1       0          1  ...       1          1      1      0

[188 rows x 31 columns]

## Removing Date Columns From Test Data

In [8]:
df = df.drop(["Date"],axis=1)
# df

NameError: name 'df' is not defined

# Normalizing Values

In [24]:
inputs  = scaler.transform(df)
inputs

array([[1., 0., 1., ..., 1., 1., 0.],
       [1., 1., 0., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 0., ..., 1., 1., 0.],
       [1., 0., 1., ..., 1., 1., 0.]])

In [0]:
x_test = []
y_test = []

In [0]:
for i in range(3, inputs.shape[0]):
    x_test.append(inputs[i-3:i])
    y_test.append(inputs[i])

In [27]:
x_test, y_test = np.array(x_test), np.array(y_test)
x_test.shape, y_test.shape

((185, 3, 30), (185, 30))

# Prediction

In [ ]:
# predicting item
y_pred = regressor.predict(x_test)

In [29]:
y_pred.shape

(185, 30)

In [31]:
y_pred

array([[0.00533584, 0.53127277, 0.5487681 , 0.48629433, 0.59536976,
        0.45768857, 0.52579564, 0.5691575 , 0.41730103, 0.48338673,
        0.52784455, 0.6591505 , 0.55442065, 0.5518533 , 0.67211115,
        0.48799962, 0.52323884, 0.53831434, 0.5187098 , 0.5811268 ,
        0.5378019 , 0.5075041 , 0.6207356 , 0.5039403 , 0.5502861 ,
        0.5680409 , 0.5848629 , 0.9997327 , 0.4488765 , 0.01645914],
       [0.01328319, 0.49838838, 0.55179346, 0.53061044, 0.5200726 ,
        0.5374479 , 0.5167641 , 0.55340594, 0.5318141 , 0.51570934,
        0.5341872 , 0.5354644 , 0.5598716 , 0.5662363 , 0.53905   ,
        0.56073874, 0.55328846, 0.5538571 , 0.548925  , 0.5422086 ,
        0.5135137 , 0.56338525, 0.5540543 , 0.56054914, 0.5319867 ,
        0.5318027 , 0.5372474 , 0.9960112 , 0.9828659 , 0.9103695 ],
       [0.0348832 , 0.47643265, 0.56132853, 0.51325816, 0.5426754 ,
        0.5340215 , 0.50459564, 0.52382994, 0.53687036, 0.51931185,
        0.5181272 , 0.5368768 , 0.5485229 , 0.